In [2]:
import pandas as pd
import numpy as np 
from sklearn import datasets
import warnings 
warnings.filterwarnings('ignore')

In [3]:
dt = datasets.load_iris()

In [7]:
df = pd.DataFrame(data=dt.data, columns=dt.feature_names)
df['target'] = dt.target

In [8]:
df.shape

(150, 5)

In [11]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [13]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [14]:
df.describe

<bound method NDFrame.describe of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1

In [16]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int32
dtype: object

In [17]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [19]:
meanData = df.mean()
print(meanData)

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
target               1.000000
dtype: float64


In [20]:
rowMeanData = df.mean(axis=1)
print(rowMeanData)

0      2.04
1      1.90
2      1.88
3      1.88
4      2.04
       ... 
145    3.84
146    3.54
147    3.74
148    3.86
149    3.56
Length: 150, dtype: float64


In [24]:
print(df['sepal length (cm)'].std(), df['petal length (cm)'].std())

0.828066127977863 1.7652982332594662


In [25]:
array = df.values

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
X = array[:,0:4]
Y = array[:,4]
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)

In [31]:
np.set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[0.222 0.625 0.068 0.042]
 [0.167 0.417 0.068 0.042]
 [0.111 0.5   0.051 0.042]
 [0.083 0.458 0.085 0.042]
 [0.194 0.667 0.068 0.042]]


In [32]:
from sklearn.preprocessing import Binarizer

In [33]:
X = array[:,0:4]
Y = array[:,4]
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)

In [34]:
np.set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
